### ISSUE TITLE
Add Tabs to Rules Modal

### ISSUE THREAD

**Issue by vincentcote87** [johnanvik/program-wars#100]
Add tabs to show the different sections of the rule book to prevent the user from scrolling to find the information. Add an arrow at the bottom of each section to jump to the next tab.

**Comment by johnanvik** [comment]
Given that the user never seems to have to scroll down enough to lose the tab heading, the "Back" and "Next" buttons seems unnecessary.

**Comment by johnanvik** [comment]
Fixed in PR #103
