### ISSUE TITLE
Credits and Rules on startpage?

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#102]
Perhaps it makes sense to have links/buttons to the credits and rules on the start page. This way people don't have to play the game to know who is responsible for it and they can understand about the game before they play it.

Or maybe have an information box under the modal that gives an overview description of the game? Just something so a new user knows what is happening. This will also help the negative space under the "Start Game" modal.

**Comment by vincentcote87** [comment]
I like this idea, I may need to redesign the first page. Currently the setting page is its own page but the setting components are populated in a modal, as far as I know you cannot stack modals. The setting components can be moved onto the actual page which could have the same header as the rest of the application showing "credits", "rules", and "report issue".
