### ISSUE TITLE
Login required to file bug report

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#107]
If a user does not have a GitrHub account (or is not logged in), clicking the "Report Bug" asks for a login. This will discourage users from giving feedback.

**Comment by johnanvik** [comment]
Looks like this is a know problem with GitHub. However, I found https://gitreports.com/ which might help.

**Comment by johnanvik** [comment]
Also found this tutorial:

http://ez34.net/2016/12/publish-anonymous-issues-on-github.html

**Comment by johnanvik** [comment]
This is a project that provides a 'comment card' interface for filing issues to GitHub.

https://github.com/benbalter/comment-card

**Comment by johnanvik** [comment]
Based on the above research, it looks like we'll need to create a hosted issue form on the server that will submit the issue for the user. 

Will need to get @sscullen involved.

**Comment by sscullen** [comment]
I will start looking into the above posted links, just let me know what else I can do.

**Comment by vincentcote87** [comment]
Just a thought while its on my mind, not sure if its more or less work or free even but what about a third party tool integrated into our app? A quick google search brought me to Doorbell.io, if worth it I could look more into it and see if it is even worth it to us.

**Comment by manavo** [comment]
Hey @vincentcote87, thanks for suggesting Doorbell.io, that's my project :)

It would allow you to capture feedback and add it to Github, it just doesn't do that automatically (you have to manually select to send it to Github and enter an issue title).

Doorbell also integrates with Zapier, so it could be automated from there if needed.

Let me know if you do want to try it @johnanvik, and if there's anything I can help with!

**Comment by sscullen** [comment]
Sorry for the lack of updates on this issue. I have put together a basic express api end point that takes a post request, then uses a GitHub personal access token to add an issue to any repo that token has pull access to. I integrated it with Google recaptcha to prevent spam, and it's adjustable  rate limited as well. I have to host it, but I can do that shortly. 

Doorbell sounds like a good solution though. I don't mind if you want to go that route. I enjoyed putting together my basic solution, so just let me know what you think.

**Comment by johnanvik** [comment]
Let's try @sscullen 's solution. This is a small-ish project and Doorbell.io may be overkill at this point. We can keep it in the back of our mind going forward and see if it is needed.

**Comment by johnanvik** [comment]
The link for reporting an issue needs to be changed to https://programmingwars.cullen.io/reportissue/

**Comment by vincentcote87** [comment]
Sorry I just noticed this last post from 11 days ago. I will send through a pull request right away.
