### ISSUE TITLE
Background image not showing on production

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#111]
PR #106 successfully built and appeared to deploy ([build url](https://travis-ci.org/johnanvik/program-wars/builds/243859191)), but the production server is showing the previous blue background.

Server-side issue?

**Comment by sscullen** [comment]
I'll take a look at the code tonight, sometimes the CSS is a bit deceiving because of the multiple nested components styles interacting.

**Comment by johnanvik** [comment]
Thanks!

**Comment by sscullen** [comment]
Looks like it was related to the how Webpack and Vue handle bundling static resources. When images or files are in the static directory, they should be referenced using an absolute file path, like:
 
/static/backgroundImg/background.png

I've changed the background-image property to:

#settingsPage {
    background-image: url("/static/backgroundImg/helloWorld.png");
    min-height: inherit;
    min-width: inherit;
  }

It was ../../static/backgroundImg/helloWorld.png before, which was using a relative path. So I can make a pull request for this, or if you want to change it with other updates Vincent makes, either way works for me. I don't fully understand how Webpack works, but more info on it can be found here:

https://vuejs-templates.github.io/webpack/static.html

**Comment by sscullen** [comment]
So I created a pull request just to learn how to do a proper pull request. Hope that's okay.
