### ISSUE TITLE
Stuck on a player

### ISSUE THREAD

**Issue by vincentcote87** [johnanvik/program-wars#114]
Sometimes out of nowhere the player turn will end but gets "stuck" with the same player. That player gets to keep playing until he/she wins or a new game needs to be initialized. cause unknown.

**Comment by johnanvik** [comment]
Ran into this testing the hack redesign. Was playing a second game, so I don't know if that is related (i.e. the result of some saved state from the first game?).

**Comment by vincentcote87** [comment]
Thanks for the tip, good place to start looking. I will be looking much deeper in what happens when a new game is initiated once I tackle issue #44.

**Comment by vincentcote87** [comment]
This issue is currently live in  the deployed version. So far 100% "success" rate when playing a second game without reloading the page.

**Comment by vincentcote87** [comment]
Observations: when playing a second game it will skip 1 player after each turn, third play through it will skip 2 players each turn. The patterns continues in this fashion, as if there is some kind of counter on each new game? Will keep investigating.

**Comment by vincentcote87** [comment]
Found a quick fix for this issue in commit 93fd8e4d1a50250a9fc350b5452fba891032a109, it will no longer skip players. There is still a bigger problem at hand though. When a player takes a turn it changes their state.hasPlayed to true than moves on to the next player, for some reason the "skipped" player never gets his state changed to true. for now added a block at endTurn() to check that the state is true.
