### ISSUE TITLE
Add delay between turns

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#118]
The UI skips to the next player on the end of a turn. A delay is needed to allow the user to see what they did. This will become more important when we have AI players.

**Comment by johnanvik** [comment]
Is this already done? I have noticed there seems to a delay between when the player clicks "end turn" and the "next players turn" modal.

**Comment by vincentcote87** [comment]
Yes, currently there is a 1.5 sec timer after each turn before the next player modal appears. 

fix #118
