### ISSUE TITLE
Tutorial Walkthrough

### ISSUE THREAD

**Issue by vincentcote87** [johnanvik/program-wars#119]
Having a separate page that guides you step by step through playing a game.

**Comment by johnanvik** [comment]
Can we create a "fixed" game with a specific deck with cards in a specific order to walk a person through the game.

**Comment by johnanvik** [comment]
Let's move to a YouTube video instead

**Comment by johnanvik** [comment]
@cccraw created video at https://www.youtube.com/watch?v=Ch8WslCgLvk
