### ISSUE TITLE
Opponent side stack "Active Score" updates too slow

### ISSUE THREAD

**Issue by vincentcote87** [johnanvik/program-wars#12]
The Active Score section showing the opponents score based on the true or false value only updates after each individual player take a turn.

**Comment by johnanvik** [comment]
Perhaps ask @sscullen about this. I seem to recall the team mentioning this in a standup meeting. He may have further insight into this.

**Comment by vincentcote87** [comment]
Fixed in pull request #115, no longer has an opponent side.
