### ISSUE TITLE
True and False Sides Ideas

### ISSUE THREAD

**Issue by vincentcote87** [johnanvik/program-wars#128]
What if we took out the true and false side "boxes" and simply added a thick line dividing the two sides. Also changing the look of the stacks to have a simpler look, maybe just the card and the add button, also without borders. Basically making it look less like containers and more like cards in front of the player.

**Comment by johnanvik** [comment]
1) Would the background of the sides still switch between green and red?
2) Doesn't it already do this with the stack update? I think having the 'borderless' stacks is a good idea.

**Comment by vincentcote87** [comment]
I played around a bit with changing some of the look of the sides, it made it harder to understand what is going on. I agree that the stack update takes care of this issue.
