### ISSUE TITLE
Coin flip dependencies

### ISSUE THREAD

**Issue by vincentcote87** [johnanvik/program-wars#151]
The main build needs to have a package installed called "vue-radial-progress" for the coin flip animation. Without it loading the web page produces a blank page.

**Comment by johnanvik** [comment]
Fixing this will allow for PR #143 to be merged back into production.

**Comment by sscullen** [comment]
Sorry for the delay! I believe I have it working now. I did a manual "npm install" to install the dependencies in the project, and added "npm install" to the post-receive git hook so it should install the new dependencies automatically in the future.
