### ISSUE TITLE
Long names should not be allowed

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#175]
#### Here is what I did...
My kid entered a REALLY long name.

#### I expected the game to...
Wasn't sure what would happen.

#### Instead the game...
- Some cards were off the screen as the cards were centred on the name.
- The turn popup didn't show all the text.

There should be a maximum on the number of characters a name can be.

**Comment by vincentcote87** [comment]
Agreed, I will add a maximum number of characters a name can be.
