### ISSUE TITLE
Improve bug reporting form and GitHub interaction

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#191]
The bug report form could use improvements:

1. Redesign form to be more attractive (see if we can get some help from Katherine)
1. Change the submitting user to someone other than Shawn. 
   (Can we have them fill in their name and have the report come from them, or is this tied to a GitHub user? May need to created a dummy GitHub account for bug report submission.)
1. Change the labels to match existing ones:
   - "Feature Request" --> "enhancement"
   - "Bug Report" --> "bug"
1. Add a "Thank you" page after they have clicked "Submit"

**Comment by johnanvik** [comment]
The form should also allow for attachment of screenshots.

**Comment by sscullen** [comment]
I have been slowly working on a new version of the reporter tool, should be up and running in a couple days. Will look at uploading screenshots, should be feasible. 

![Test image](https://www.emojibase.com/resources/img/emojis/apple/x1f389.png.pagespeed.ic.FkjckyE3hU.png)

**Comment by sscullen** [comment]
Also, regarding the user that submits the bug report, I think it is tied to the personal access token used to submit the issue. I will look at the API to see if a different name can be used for a submitter of the issue, but if not then I think a dummy account for the project would be the best option, and changing the personal access token is trivial, as I would just have to change an environment variable on the server.

**Comment by JaceRiehl** [comment]
I don't have access to this code.
