### ISSUE TITLE
Create an annotated screenshot

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#208]
To assist new contributors, an annotated screenshot that shows which UI element corresponds with which component would be very useful.

**Comment by vincentcote87** [comment]
I have created this "colourful" page showing the main components. 
I can't seem to be able to add it to the wiki page.
![v1_5layout](https://user-images.githubusercontent.com/19965014/30946734-fd447bd4-a3c2-11e7-9ce0-4665aef63445.png)

**Comment by vincentcote87** [comment]
Was able to add the image to the wiki.
