### ISSUE TITLE
Warnings when running unit tests

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#223]
When  I run the unit tests locally, I get a number of errors/warnings with the Card tests:

![image](https://user-images.githubusercontent.com/28762049/32628107-f9df4fcc-c551-11e7-9a2f-fcb3840e4a06.png)

It looks like these are coming from here:

![image](https://user-images.githubusercontent.com/28762049/32628163-28c16438-c552-11e7-85ef-a7ff565b7578.png)

**Comment by JaceRiehl** [comment]
This is fixed by switching the $store calls to maps. Dependent on #332
