### ISSUE TITLE
Make survey branch live

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#234]
The user study branch needs to be pushed to production once ready.

**Comment by vincentcote87** [comment]
-Disable new game button
-Change AI names
-Add a games played tracker (e.g. 1/3 games played) in the winner modal

**Comment by vincentcote87** [comment]
@johnanvik @cccraw  Please checkout live version for review, lots of changes made. I definitely need a second pair of eyes on it.

**Comment by johnanvik** [comment]
Need to address #236, #237, #238, and #239.

**Comment by vincentcote87** [comment]
Live version has been updated.

**Comment by johnanvik** [comment]
Game went live for study in late November.
