### ISSUE TITLE
Make sure questions have unique identifiers

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#243]
For analysis, the questions need unique ids (eg. Q4-C for Question 4 using C)

**Comment by cccraw** [comment]
Changed Question Identifiers

**Comment by johnanvik** [comment]
Looks like a few got missed on the post survey.

![image](https://user-images.githubusercontent.com/28762049/33278022-7c4e9f90-d357-11e7-997a-3b3513b0f7ac.png)

**Comment by johnanvik** [comment]
Pre-game survey looks good.

**Comment by cccraw** [comment]
Fixed Post survey

**Comment by johnanvik** [comment]
Thanks!
