### ISSUE TITLE
Use CSSLint?

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#282]
Do we have any CSS style files? Would CSSLint be useful?

https://github.com/CSSLint/csslint/wiki/Rules

**Comment by JaceRiehl** [comment]
I could see this being useful. We already have ESLint in the repo (although it doesn't seem to be working right now) and Im not sure how they will interact with each other.

**Comment by johnanvik** [comment]
I also found this engine for CodeClimate that seems similar.

https://docs.codeclimate.com/docs/stylelint
