### ISSUE TITLE
Is ESLint running?

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#283]
Looking at the .eslint.ignore file, I'm not sure that ESLint is actually running on the code as it looks like the `src` directory is ignored.

**Comment by JaceRiehl** [comment]
I didn't see this before I replied to #282. It doesn't seem to be working. I was using ESLint in one of my repos with WebStorm and you could see it running, which I can't currently see with this repo.

**Comment by JaceRiehl** [comment]
It's working in the index.html file, so it might only be working at the root.
