### ISSUE TITLE
Deck balancing 

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#310]
**Gameplay Problem**
I think the number of each card in the deck needs to be changed a bit, there will be some rounds that I start where I can't make a move. 

The cards we need the most are probably instruction cards.

**Screenshots**

**Comment by johnanvik** [comment]
This makes sense given recent changes. There is a speadsheet I created to help figure out the number of cards to have in the deck relative to the number of players. Look in the ```development``` directory.

**Comment by JaceRiehl** [comment]
Is this still an issue?

**Comment by JaceRiehl** [comment]
![screenshot 2018-07-06 16 00 43](https://user-images.githubusercontent.com/26579097/42402046-c06c5f78-8135-11e8-9811-f89654ff9c20.jpg)
From Slack

**Comment by johnanvik** [comment]
Fixed PR #476
