### ISSUE TITLE
Have a single target for the  game.

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#314]
I'm wondering if it would help to have the game only have a single target, say 100 instructions? It might make some things simpler (e.g. the starting modal, the player only has to remember one target).

**Comment by JaceRiehl** [comment]
This is hard to say, some people really like the reward they get from winning a long game, such as civilizations, and others would much rather have short games with multiple wins. My guess would be that a majority of players like the shorter games with more restarts. I think 100 would be a benefit to the game.

**Comment by groadybones** [comment]
Fixed in my most recent pull request
