### ISSUE TITLE
Playing Virus on an Overclocked opponent

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#316]
**Describe the bug**
When you have an Overclock in play, and an opponent plays a Virus on you, it removes the Overclock (correctly) and also applies the Virus (incorrectly). As these two cards a opposites, the correct action should be to remove the Overclock (i.e. instruction no longer doubled). Otherwise this seems too punitive.

**Comment by JaceRiehl** [comment]
I haven't been able to recreate this. Do you have any more information about how to recreate this?

**Comment by JaceRiehl** [comment]
I can't recreate this, so for the mean time I'm going to assume this got fixed along the way.
