### ISSUE TITLE
Only one copy of Safety cards

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#324]
**Describe the bug**
I noticed when playing that an opponent had two Firewall cards.

**To Reproduce**
1. Play game

**Expected behavior**
There should only be one copy of the safety cards (Firewall, Anti-virus, Generator) to increase their value.

**Comment by JaceRiehl** [comment]
This is due to the each player not getting an individual deck. Would you like me to separate the big deck into individual decks or only put one copy of each safety card in the deck to be separated amongst the players?

**Comment by johnanvik** [comment]
One copy of the safeties in the shared deck. Across the game, only one person can have each safety. This is different than the Remedies (Overclock, Battery) where there are twice as many as the corresponding Hazard.

**Comment by johnanvik** [comment]
I just peeked at Deck.js. I forgot that we had the number of each type of card dependent on the number of people playing. That would be where the problem came from.
