### ISSUE TITLE
Firebase issue 

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#328]
There is a major issue with the firebase deployment. I can get firebase to read the index.html file but when it reads it is not injecting the App.vue file into the index file. This is causing the website to show a blank screen (unless you put something that isn't Vue content.

**Comment by johnanvik** [comment]
Related to #53

**Comment by JaceRiehl** [comment]
I was able to push a testing website to firebase, so it looks like it's something wrong with the project.

**Comment by johnanvik** [comment]
I'm  getting this error. Ideas?

![image](https://user-images.githubusercontent.com/28762049/41790086-a893bba8-760e-11e8-8449-17b9db2c2b46.png)

**Comment by JaceRiehl** [comment]
In the firebase.json the public directory points to 'dist' maybe it needs a relative file path so './dist'

**Comment by johnanvik** [comment]
I'm also wondering if I need to `npm build`? Looking into that now.

**Comment by JaceRiehl** [comment]
Oh right, yes you need to run 'npm run build' to update the website every time.

**Comment by johnanvik** [comment]
(embarrassed) Yeah, building the website before deploying it was a good idea.
