### ISSUE TITLE
Policy for version numbering

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#358]
We should establish a policy about how versioning of the software should go.

For example, what do we consider as "major release" and what is a "minor release"? What about indicating bug fix/feature inclusion? Do we what to try to include a build id?

To start the discussion:
* **Major release**: A complete overhaul of the UI or something similar to that scale.
* **Minor release**: Indicates the sprint/iteration
* **Pull Request/Patch**: Indicates an update from a pull request merge

Not sure if we need to go deeper than that.

So under this scheme, `v1.7.10` means the 10th merged pull request of the 7th iteration of the 1.0 product line.

**Comment by JaceRiehl** [comment]
The suggestions you have seem pretty good. I think It would be overkill to update the release with each bug. If it's a serious enough of a bug then I suppose it would be merged pretty quickly after the bug fix is pushed. It terms of a major and minor releases I think what you have is perfect.

**Comment by johnanvik** [comment]
So we would only have major/minor releases that correspond to iteration. That's what we are doing now, so that would not change things.

As of now, the live site reflects the latest version of the `master` branch. I can potentially see an issue if we only report the major & minor issue to the user that what they report does not accurately reflect the version that is live (which may contain bug fixes). So this really comes down to a decision about the deployment policy.
