### ISSUE TITLE
Can't view opponents stacks after they've played a firewall card

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#363]
John Jr. provided the feedback that he couldn't see the opponents stacks after they've played a firewall card. This is because the modal used to view their stacks is the same one as the hack modal so it does a check of viewable stacks. Is this something that we want to be able to happen?

**Comment by JaceRiehl** [comment]
![screenshot 2018-07-03 09 00 02](https://user-images.githubusercontent.com/26579097/42227790-82729d1a-7e9f-11e8-83d5-ec8932b682ee.jpg)
From slack.

**Comment by johnanvik** [comment]
@JaceRiehl, can you please see if this is still an issue? If not, close it.

**Comment by JaceRiehl** [comment]
The modal used for this is the same as the modal used to hack, so it is still an issue.

**Comment by johnanvik** [comment]
See also #433

**Comment by groadybones** [comment]
Gonna close this cause issue #433 should take care of this
