### ISSUE TITLE
New card ideas

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#365]
From John Jr. on slack. 
![screenshot 2018-07-03 14 44 41](https://user-images.githubusercontent.com/26579097/42243761-a459b500-7ecf-11e8-9716-dc53449ec74a.jpg)

**Comment by johnanvik** [comment]
Maybe consider adding these when we look at #467.

**Comment by groadybones** [comment]
apart from the lag card, theres something similar to each of these in the cards channel on slack so I will add it there and close this here
