### ISSUE TITLE
Overclock and Virus too powerful?

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#379]
**Gameplay Problem**
If a player gets an overclock, it doubles their score. This means that it can be an instant win. Similarly, a virus halves the score, which may make progress frustratingly slow. Perhaps adjusting these to have the overclock be 1.5x or 1.25x and the virus be 0.25x would be better?

**Comment by JaceRiehl** [comment]
I was thinking the same thing, the overclock is technically an instant win card if they get to half the score that the opponents can do nothing about. I think 25% or 50% would be way better. I would have to play with the numbers.
