### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#380]
This has been an issue from almost the start of the project. Is the game "Programming Wars" or "Program Wars"? The GitHub is called "Program Wars" and the URL says "Programming Wars". We need to pick one (or a different name - see #135) and stick with it.

**Comment by JaceRiehl** [comment]
I personally like 'Programming Wars' better, I think it's more catchy and gives the user a clearer idea of what the game is about.

**Comment by johnanvik** [comment]
I am preparing the camera-ready copy for SIGCSE 2019. In the paper, I unless there is an objection, I'm going to go with "Program Wars" as it seems less of a mouthful.

**Comment by johnanvik** [comment]
I can change the name in the paper anytime before the end of November.

**Comment by JaceRiehl** [comment]
I think program wars is awesome, Ill go through and change the reference in the game to make it more consistent.
