### ISSUE TITLE
Use GitReports for user issue reporting

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#381]
See https://gitreports.com

**Comment by johnanvik** [comment]
The URL for the reporting is:

https://gitreports.com/issue/johnanvik/program-wars

**Comment by johnanvik** [comment]
Noticed that the report will be submitted as if @JaceRiehl did it (see #182). Can't see how to change this.

**Comment by johnanvik** [comment]
@JaceRiehl, you can update the link now.

**Comment by JaceRiehl** [comment]
@johnanvik I think that happened because I initially tried to set up the repo with GitReports.
