### ISSUE TITLE
Create a backstory for the game 

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#392]
From July 17 meeting: Create a backstory for the game to help in the creation of the name.

**Comment by JaceRiehl** [comment]
Related to #380

**Comment by johnanvik** [comment]
@JaceRiehl Can you add the items from your notes (if you still have them)?

**Comment by johnanvik** [comment]
I'm partial to a combination of "AI is sentient" and "you are on a game show" (code gladiator?)

**Comment by groadybones** [comment]
I added a story/name, if you've ever played GH3 warriors of rock, think of the opening video where the guy is battling his way up the mountain to face the god of rock.

**Comment by groadybones** [comment]
It didn't update the doc, I probs have to push it.

**Comment by groadybones** [comment]
[Program.wars.background.story.docx](https://github.com/johnanvik/program-wars/files/3128921/Program.wars.background.story.docx)

**Comment by groadybones** [comment]
The backstory has been decided on so I'm gonna close this
