### ISSUE TITLE
Grouping repetitions

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#40]
I had a case where I had the following stacks:
[ I3, R2 ]
[ I2, R2 ]
[ I1 ]

My hand had a G5 card.

I was not able to group the I3 and I2 cards, as their totals (with the repetition is 10, but I could group the I2 and I1 as (with the R2) the total is 5.

Is this correct behaviour?

**Comment by johnanvik** [comment]
Assuming that the above situation is handled correctly, what about the following situation?
[ I2, Rx, V3] and have a G6 in your hand. It seems like you should be able to protect this with a group card, but as the game is implemented, you can only group two stacks, not one.

**Comment by vincentcote87** [comment]
I think group assumes two or more stacks and not grouping inside a single stack. Could be changed though. As far as your first question, from my understanding that is the correct behaviour. It takes the total value of the stack not the Instruction cards only.

**Comment by johnanvik** [comment]
I think you are right. The first behaviour is correct. But I'm also thinking we should allow grouping of single stacks for when a player has a good stack they want to protect. I'll open an enhancement about this and we can perhaps do some user testing.
