### ISSUE TITLE
UI issue on bigger monitors

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#402]
There is an issue on bigger monitors with the component not being long enough. This is good for smaller monitors but when the themes are applied it shows the flaw. I'm going to apply a div at the end that fills this space, but It's going to cause a scroll bar for smaller monitors. I'm not sure what a better solution to this is. 
![screenshot 2018-07-27 10 55 04](https://user-images.githubusercontent.com/26579097/43335640-f0e11600-918c-11e8-85e6-52b6966f479b.jpg)

**Comment by groadybones** [comment]
I don't see the scroll bar as an issue and its not a big enough problem to bother spending time trying to figure out
