### ISSUE TITLE
Allow Battery Backup to be played without a Power Outage

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#409]
**Gameplay Problem**
If we can play an Overclock without a Virus, it seems like you should be able to play a Battery Backup in case someone uses a Power Outage on you. Thoughts?

**Screenshots**
![image](https://user-images.githubusercontent.com/28762049/43341775-be09bb36-919d-11e8-8076-dc231a660f2d.png)

**Comment by JaceRiehl** [comment]
Since this card is purely defensive and has no benefit to keep in the users hand, I think this is a great idea.
