### ISSUE TITLE
[UI] Change overall layout

### ISSUE THREAD

**Issue by mkshiblu** [johnanvik/program-wars#417]
The current UI design could use some improvement in terms of User Experience (UX). For example, there is a separate discard button to discard the selected card. However, if we provide a discard button as a close/ (x) symbol at the top right corner of each card we could easily close it. 

Besides, I think it is more user-friendly if the paths are pushed to the side and the cards are shown either in the center or bottom.

![wbeview](https://user-images.githubusercontent.com/15908043/43990319-7912140c-9d7c-11e8-9d44-6c7e79fe5251.JPG)

I think this design is easier to make responsive than the current layout design.

**Comment by johnanvik** [comment]
+1 for the updated design.

I'm not sure about the "close" button on the cards. This could be confusing and error-prone.

**Comment by groadybones** [comment]
This isn't even the current UI so I'm closing
