### ISSUE TITLE
Cannot play Malware if an different opponent has Firewall

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#421]
Submitter: John Anvik jr
Email: john.anvik20@lethsd.ab.ca
In a three-player game, player 3 plays a firewall. Player 1 has a malware card, but when they try to play it they cannot infect player 3, which makes sense, but they can't infect player 2 either, which does not.

**Comment by JaceRiehl** [comment]
I can't recreate this. A firewall card is used to block hack cards so this doesn't make sense. I tried malware with an anti-virus card played as well as hack cards with

**Comment by johnanvik** [comment]
Until someone else reproduces this and reports it, let's close the issue.
