### ISSUE TITLE
"Rules" menu item doesn't work

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#436]
**Describe the bug**
When I select the "Rules" item on the menu, nothing happens.

**To Reproduce**
1. Go to the game title page
2. Click on the button for the side menu
3. Click on "Rules"
4. Nothing happens

**Expected behaviour**
The rules for the game are shown.

**Comment by JaceRiehl** [comment]
I can't recreate this.

**Comment by johnanvik** [comment]
I was able to recreate this on production in Chrome (on Windows) and Firefox (on Linux).

**Comment by JaceRiehl** [comment]
All of the browsers are working for me on MacOS. Is it only the start page rules that doesn't work for you?

**Comment by JaceRiehl** [comment]
The Rules was working for me on the development server but it's not working for me on the production.

**Comment by JaceRiehl** [comment]
This is going to be a big deal for the user study but I can not figure out what is wrong. For me it works on the dev server but not the production. It's implemented exactly the same as all of the other buttons. @vincentcote87 @mkshiblu would either of you guys be able to look at this in any of the files (SettingsComponent, MainComponent, or TutorialComponent) and see if anything stands out to you? It's in the middle of the HTML code at the top of the files.

**Comment by JaceRiehl** [comment]
@mkshiblu This fixed it. Great catch!
