### ISSUE TITLE
Change playing field to be conditional cards

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#473]
(@groadybones originally suggested this in #469)

**Is your feature request related to a problem? Please describe.**
Players seem irked about the randomness of having one of two playing fields active.

**Describe the solution you'd like**
Instead of having true/false playing fields they're called then and else. A new class of cards is scattered throughout the deck called conditional cards. These cards will say, "if " and the game responds by setting the active playfield according to the current active conditional. Some examples of conditions that a card could contain:

 * if(active instructions > 10)
 * if(# of groups < 5)

Pros:
-gives players slight control over the active playfield
-adds another aspect of competition between players
-follows more closely the principles of a conditional

Cons:
-could be confusing
-might be frustrating for players
-lot of work to implement

**Describe alternatives you've considered**
Another idea could be to have a "conditional" card that players can use in or on a stack to boost that particular stack. Sort of like how repetitions boost an instruction.

**Comment by johnanvik** [comment]
So is the conditional global? Meaning that a player places it in a "global" area of the board and it affects everyone? Or do they have an area of their playing field (there would only be one now) that they play a conditional on and then it affects the player's stacks?

**Comment by groadybones** [comment]
I wanted your input on that actually, what do you think it should be? If its global that adds the extra competitive aspect because players will be fighting over the active conditional but that could also be a source of frustration for the user so maybe it'd be better to set it as a player by player thing but then a player could just lock in the side they want to go with and discard every other conditional card they come across. Maybe that presents an opportunity for new type of hack card though, one that allows players to mess with another players conditional

**Comment by johnanvik** [comment]
I'm not a fan of having global state, so I think we should have this as an individual decision. The player can have one active at a time and can replace it if they get one they think is better.

**Comment by johnanvik** [comment]
The conditional could be another effect like the cybersecurity and defence cards. I guess it will depend on what we decide that these cards do.

**Comment by groadybones** [comment]
I like the sounds of that, if we design these cards well, the player will have to keep a close eye on the conditional cause their own actions could mess up their plan. It also present the opportunity for us to make new hacker cards that let opponents mess with each others conditionals.

**Comment by groadybones** [comment]
see issue #481
