### ISSUE TITLE
Make number of cards proportional to number of players

### ISSUE THREAD

**Issue by vincentcote87** [johnanvik/program-wars#48]
I played a few rounds with my step son and found we often had to go many rounds before one of us getting an Instruction card. Currently has 24 all together.

**Comment by johnanvik** [comment]
I observed the same thing when I was playing earlier. I seemed to be getting lots of the other cards and waiting to get instruction cards. I think we need to find the right instruction:group:repetition ratio for the cards. Not sure what it is now.

Also, perhaps we should make the number of cards proportional to the number of players. That way the ratio stays the same no matter the number of players (something you can't do with physical cards!)

**Comment by johnanvik** [comment]
I created this spreadsheet to figure out the number of cards to have in the deck per player. This way we can play with the numbers easier.

[Card Frequncies.xlsx](https://github.com/johnanvik/program-wars/files/1050639/Card.Frequncies.xlsx)

**Comment by johnanvik** [comment]
Tried adding I4, G7, G8, and R4. This resulted in a game that ended very quickly (Like one or two turns).
