### ISSUE TITLE
Players can still win without achieving target score

### ISSUE THREAD

**Issue by groadybones** [johnanvik/program-wars#486]
**Gameplay Problem**
The game rules specify that a player has to have a playfield score higher than or equal to the target score in order to be considered a winner, however players are declared winners if their total score after bonuses are tallied is equal or higher than the target score. Easy fix, just have to change which score value is being tested when the winners are calculated, I'm thinking just a nested conditional that checks which is the higher playfield score and compares it to the target score.

**Comment by johnanvik** [comment]
Looks like the docs need updating to reflect that a round ends when a player reaches the target score, but the winner of the game is the one with the highest total score. Will need to make it clear that a player can still win the round even if they don't reach the goal.

**Comment by strinsberg** [comment]
I will update the RulesModal text to explain that the game ends at a given score, but the winner is determined by the final score after considering the bonus objectives.
