### ISSUE TITLE
Select cards to redraw

### ISSUE THREAD

**Issue by JaceRiehl** [johnanvik/program-wars#497]
Submitter: Josh
In my opinion I think the best defensive card was the firewall and the best offensive card was the power outage and the hacker card.What i think would be a great addition is when you redraw you get to choose which cards you keep when  you redraw.

**Comment by groadybones** [comment]
I had the same redraw idea shortly after I started working on the project. Dr Anvik and I decided that redrawing cards must come at a cost to the player hence why they're not allowed to choose any cards they want to keep when they choose to do so. I am thinking it'd be a good idea to make it so power outages aren't playable in the first round cause on multiple occasions I've been hooped straight from the get go cause I can't play any cards for the first half of the game.

**Comment by johnanvik** [comment]
This is from one of the participants in a Destination Exploration session that ran. The participants were around 10 years old and spent the entire time playing a "2-player hot seat" with another of the participants. At the end of the session, I asked them to submit some feedback about what cards they most liked and disliked and suggestions for improvements.

**Comment by groadybones** [comment]
OOOHHH that makes way more sense! I thought maybe you had asked Jace to quickly review and give feedback. There isn't too much new information to go off of which is a little unfortunate.

**Comment by johnanvik** [comment]
@hastar07 will be changing many of the cards mentioned here, so this issue is becoming obsolete.
