### ISSUE TITLE
Problem with hack cards

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#54]
When a hacker card is selected, and then a player is selected (so you can hack them,) the hack card is deselected and you have to click on it again.

**Comment by johnanvik** [comment]
Perhaps when the hack card is selected, the other player's stacks are automatically expanded. As long as there are not too many players, this might be OK.

**Comment by vincentcote87** [comment]
I have implemented @johnanvik suggestion to expand automatically when hack card is clicked, as expected it does not work well with more than two players. Will explore other solution.

**Comment by vincentcote87** [comment]
commit c74df686ad5c090bcf448c12eb97a4c19207a5a7 has the above implementation.

**Comment by johnanvik** [comment]
As the primary issue seems to be the hack card deselecting after the player expands an opponent's deck, could we just switch focus back to the hack card afterwards? Is the only time that a player needs to see the expansion when a hack card is played?

**Comment by vincentcote87** [comment]
Yea mostly, the only other time a player might look at it is to see where they stand before taking a turn. I would like to try and make the card not de-select when clicked elsewhere on the page until it is added to the stack, another card is clicked or the same card is re-clicked to de-select?
