### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by johnanvik** [johnanvik/program-wars#94]
The current test coverage is [![Test Coverage](https://codeclimate.com/github/johnanvik/program-wars/badges/coverage.svg)](https://codeclimate.com/github/johnanvik/program-wars/coverage). Let's see if we can pull that up to a yellow or green level.

**Comment by johnanvik** [comment]
This may be useful:

https://testingbot.com/support/other/travis-ci

**Comment by JaceRiehl** [comment]
Dependent on #293

**Comment by johnanvik** [comment]
Looks like TestingBot is a paid service. So that is out.

**Comment by groadybones** [comment]
I'm gonna close this because its restating issue #478 but is less relevant to the current project
