### ISSUE TITLE
Redesign Opponent Section

### ISSUE THREAD

**Issue by vincentcote87** [johnanvik/program-wars#99]
Remove the opponent section, add a "bar" between the players hand and play field that displayed each player and current scores. When the hack card is clicked a "hack" button appears, when clicked a modal pops up showing the different hack options. Players names should be in a tab in top of the modal.

**Comment by johnanvik** [comment]
Just clicking the hack card should open the model. I'm not sure the extra step of clicking the button is needed. As long as they can close the modal if they change their mind about hacking.
